mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('add', views.add_question, name='add_question'),
    path('edit', views.view_edit, name='view_edit'),
    path('delete', views.delete_question, name='delete_question'),
    path('save_edit', views.edit_question, name='edit_question'),

    path('rsp', views.responsive_show, name='rsp'),

    path('<int:question_id>/add', views.add_choice, name='add_choice'),
    path('<int:question_id>/edit', views.edit_delete_choice, name='edit_choice'),
    path('<int:question_id>/delete', views.edit_delete_choice, name='delete_choice'),
    path('<int:question_id>/save', views.save_choice, name='save_choice'),

    path('table_question/', views.show_table_question, name='show_table_question'),
    path('table_question/<int:question_id>/table_choice/', views.show_table_choice, name='show_table_choice'),
]

mysite/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from datetime import date
from itertools import chain

from .models import Choice, Question

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def add_question(request):
    Question.objects.create(question_text = request.POST['question_txt'], 
                                pub_date = date.today())
    return HttpResponseRedirect(reverse('polls:index'))

def delete_question(request):
    if request.POST.getlist('question_id'):
        selected_question = [ Question.objects.get(pk=q_id) for q_id in request.POST.getlist('question_id')]
        for sel_q in selected_question:
            sel_q.delete()
        return HttpResponseRedirect(reverse('polls:index'))
    else:
        latest_question_list = Question.objects.order_by('-pub_date')[:5]
        context = {'latest_question_list': latest_question_list,
                    'error_message': "You didn't select a question.",}
        return render(request, 'polls/index.html', context)
        
def view_edit(request):
    if request.POST.getlist('question_id'):
        selected_question = [ Question.objects.get(pk=q_id) for q_id in request.POST.getlist('question_id')]
        context = {"sel_question_list": selected_question,}
        return render(request, 'polls/edit_question.html', context)
    else:
        latest_question_list = Question.objects.order_by('-pub_date')[:5]
        context = {'latest_question_list': latest_question_list,
                    'error_message': "You didn't select a question.",}
        return render(request, 'polls/index.html', context)
        
def edit_question(request):
    for key in request.POST:
            if 'question' in key:
                q_id = int(key.split("_")[2])
                selected_question = Question.objects.get( pk=q_id )
                selected_question.question_text = request.POST[ key ]
                selected_question.save()
    return HttpResponseRedirect(reverse('polls:index'))

def show_table_question(request):
    question_fields = Question._meta.fields
    question_list = Question.objects.values_list().all()
    context = {"question_fields": question_fields,
            "question_list": question_list,}
    return render(request, 'polls/table_question.html',context)

def show_table_choice(request, question_id):
    choice_fields = Choice._meta.fields
    choice_list = Choice.objects.filter(question_id=question_id).values_list()
    print(list(set(chain.from_iterable(
    (field.name, field.attname) if hasattr(field, 'attname') else (field.name,)
    for field in Choice._meta.get_fields()
    # For complete backwards compatibility, you may want to exclude
    # GenericForeignKey from the results.
    if not (field.many_to_one and field.related_model is None)
    ))))
    context = {"choice_fields": choice_fields,
            "choice_list": choice_list,}
    return render(request, 'polls/table_choice.html',context)

def responsive_show(request):
    question_list = Question.objects.all()
    context = {"question_list": question_list}
    return render(request, 'polls/responsive_show.html',context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
        
def add_choice(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question,
            "action":"Add"}
    return render(request, 'polls/add_edit_choice.html', context)        

def edit_delete_choice(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        if (request.POST['action']) == "Delete":
            selected_choice.delete()
            return render(request, 'polls/detail.html', {'question': question,})
        elif (request.POST['action']) == "Edit":
            context = {'question': question,
                "sel_choice_obj": selected_choice,
                "action":"Edit"}
            return render(request, 'polls/add_edit_choice.html', context)

def save_choice(request, question_id):
    if ("save_edit" in request.POST):
        selected_choice = Choice.objects.get(pk=request.POST['choice_id'])
        selected_choice.choice_text = request.POST['choice_txt']
        selected_choice.save()
    elif ("save_add" in request.POST):
        question = get_object_or_404(Question, pk=question_id)
        question.choice_set.create(choice_text = request.POST['choice_txt'])

    return HttpResponseRedirect(reverse('polls:detail', args=(question_id,)))

mysite/polls/templates/polls/add_edit_choice.html
<h1>{{ question.question_text }}</h1>

<form action="{% url 'polls:save_choice' question.id %}" method="post" oninput="o1.value = choice_txt.value">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        {% if action == "Edit" %}
            {% if sel_choice_obj.id == choice.id %}
                <input type="radio" name="choice_id" id="choice{{ forloop.counter }}" value="{{ choice.id }}" checked>
                <output name="o1" >{{ choice.choice_text }}</output><br>
            {% else %}
                <input type="radio" id="choice{{ forloop.counter }}" value="{{ choice.id }}" disabled>
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endif %}
        {% elif action == "Add" %}
            <input type="radio" id="choice{{ forloop.counter }}" value="{{ choice.id }}" disabled>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% if forloop.last %}
                <input type="radio" checked>
                <output name="o1" ></output><br>
            {% endif %}
        {% endif %}
    {% endfor %}

    {% if not question.choice_set.all and action == "Add" %}
        <input type="radio" checked>
        <output name="o1" ></output><br>
    {% endif %}

    <br>
    {{action}} choice :
    <input type="text" name="choice_txt" value="{{ sel_choice_obj.choice_text }}">
    <br><br>
    {% if action == "Edit" %}
        <input type="submit" name=save_edit value="Save">
    {% elif action == "Add" %}
        <input type="submit" name=save_add value="Save">
    {% endif %}
</form>


{% comment %}
<!-- <br>
<p><b>Select choice to delete</b></p>
<form action="{% url 'polls:delete_choice' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice_id" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
        
</form> -->
{% endcomment %}

mysite/polls/templates/polls/detail.html
<h1><a href="{% url 'polls:index' %}">{{ question.question_text }}</a></h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if question.choice_set.all %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
        <br>
        <input type="submit" value="Vote">
        <input type="submit" formaction="{% url 'polls:add_choice' question.id%}" value="Add">
        <input type="submit" name="action" formaction="{% url 'polls:edit_choice' question.id %}" value="Edit">
        <input type="submit" name="action" formaction="{% url 'polls:delete_choice' question.id %}" value="Delete">
    </form>
{% else %}
    <p>No choice are available.</p>
    <form action="{% url 'polls:add_choice' question.id %}" method="post">
        {% csrf_token %}
        <input type="submit" name="action" value="Add">
    </form>
{% endif %}

mysite/polls/templates/polls/edit_question.html
<h1>Edit Question</h1>

<form action="{% url 'polls:edit_question' %}" method="post"">
    {% csrf_token %}
    {% for question in sel_question_list %}
        <input type="checkbox" checked disabled>
        <input type="text" name="question_txt_{{ question.id }}" value="{{ question.question_text }}"><br>
    {% endfor %}
    <br><br>
    <input type="submit" value="Save">
    <input type="submit" formaction="{% url 'polls:index' %}" value="Cancel">
</form>

mysite/polls/templates/polls/index.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% if latest_question_list %}
    <form action="" method="post">
        {% csrf_token %}
        {% for question in latest_question_list %}
            <input type="checkbox" name="question_id" id="question{{ forloop.counter }}" value="{{ question.id }}">
            <a href="{% url 'polls:detail' question.id %}"><b>{{ question.question_text }}</b></a><br>
        {% endfor %}
        <br>
        <input type="submit" formaction="{% url 'polls:view_edit' %}" value="Edit">
        <input type="submit" formaction="{% url 'polls:delete_question' %}" value="Delete">
        <input type="submit" formaction="{% url 'polls:show_table_question' %}" value="Table">
    </form>
    <br>
    <form action="{% url 'polls:add_question' %}" method="post">
        {% csrf_token %}
        Add Question : <input type="text" name="question_txt" value="">
        <input type="submit" value="Add">
    </form>
{% else %}
    <p>No polls are available.</p>
    <form action="{% url 'polls:add_question' %}" method="post">
        {% csrf_token %}
        Add Question : <input type="text" name="question_txt" value="">
        <input type="submit" value="Add">
    </form>
{% endif %}

mysite/polls/templates/polls/responsive_show.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
* {
  box-sizing:border-box;
}

.left {
  background-color:#2196F3;
  padding:20px;
  float:left;
  width:20%; /* The width is 20%, by default */
  border-style: solid;
}

.main {
  background-color:#f1f1f1;
  padding:20px;
  float:left;
  width:60%; /* The width is 60%, by default */
  border-style: solid;
}

.right {
  background-color:#4CAF50;
  padding:20px;
  float:left;
  width:20%; /* The width is 20%, by default */
  border-style: solid;
}

/* Use a media query to add a break point at 800px: */
@media screen and (max-width:800px) {
  .left, .main, .right {
    width:100%; /* The width is 100%, when the viewport is 800px or smaller */
  }
}
</style>
</head>
<body>

<h2>Media Queries</h2>
<p>Resize the browser window.</p>

<p>Make sure you reach the breakpoint at 800px when resizing this frame.</p>

{% for qst in question_list%}
    <div class="right">
        <p>{{qst.question_text}}</p>
    </div>
{% endfor %}

</body>
</html>

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

mysite/polls/templates/polls/table_choice.html
<table border="1">
    <tr>
        {% for field in choice_fields%}
            <th>{{field.name}}</th>
        {% endfor%}
    </tr>
    {% for qst in choice_list%}
    <tr>
        {% for attr in qst%}
            <td>{{attr}}</td> 
        {% endfor%}
    </tr>
    {% endfor%}
    
</table>

mysite/polls/templates/polls/table_question.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
</head>

<body>

<table border="1">
    <tr>
        {% for field in question_fields%}
            <th>{{field.name}}</th>
        {% endfor%}
    </tr>
    {% for qst in question_list%}
    <div style="overflow-x:auto;"></div>
    <tr>
        {% for attr in qst%}
            {% if forloop.counter0 == 1 %}
                <td><a href="{% url 'polls:show_table_choice' qst.0 %}">{{attr}}</a></td>
            {% else %}
                <td>{{attr}}</td>
            {% endif %}   
        {% endfor%}
    </tr>
    </div>
    {% endfor%}
    
</table>

</body>